# Generated by Django 5.1.3 on 2025-04-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_rename_mobile_number_profile_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
