# Generated by Django 5.2 on 2025-04-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_menuitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='mobile_number',
        ),
    ]
