# Generated by Django 5.2 on 2025-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_full_name_contactmessage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='meat_category',
            field=models.CharField(choices=[('VEG', 'Vegetarian'), ('CHK', 'Chicken'), ('BEF', 'Beef'), ('PRK', 'Pork'), ('FIS', 'Fish'), ('SEA', 'Seafood')], default='VEG', max_length=3),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
