# Generated by Django 5.1.3 on 2025-04-27 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_menuitem_meat_category_alter_menuitem_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_items", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="meat_category",
            field=models.CharField(
                choices=[
                    ("VEG", "Vegetarian"),
                    ("CHK", "Chicken"),
                    ("BEF", "Beef"),
                    ("PRK", "Pork"),
                    ("FIS", "Fish"),
                ],
                default="VEG",
                max_length=3,
            ),
        ),
    ]
