# Generated by Django 5.1.3 on 2025-05-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_menuitem_likes_alter_menuitem_meat_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("preparing", "In Progress"),
                    ("ready", "Ready"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="preparing",
                max_length=20,
            ),
        ),
    ]
